server:
  port: 8083


spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/everyparking
    username: user1
    password: 12345
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace